### ISSUE TITLE
REQUEST FOR HELP

### ISSUE THREAD

**Issue by morgothx** [thayronarrais/docker-laravel-postgres-nginx#3]
Hi, thank you for this proyect.

I want to ask you if its posible to run composer install when the container start (I put a command instruction on the docker-composer file but then when the install finish the container stops)

Also I want to know if it's possible to build an image with the laravel app and put it on docker hub

Thanks againa

**Comment by thayronarrais** [comment]
Hello, sorry for waiting.
Yes, you do, but you should know starting the command, 
Generally I use in the container in execution and not in the docker-composer file.
Exists many projects in docker hub for laravel, my idea is automate laravel using github or gitlab, and with one command, you can use your application.

**Comment by morgothx** [comment]
I forgot about this, thank you, I solve it by putting a service for composer in my compose file
